# Change these first
owner: robertormzg # Your GitHub organization or username, where this repository lives
repo: upptime-dgdc # The name of this repository

sites:
  - name: Divulgacion de la Ciencia UNAM
    url: http://www.dgdc.unam.mx
  - name: Universum
    url: http://www.universum.unam.mx
  - name: Ciencia UNAM
    url: http://ciencia.unam.mx
  - name: Revista Como ves
    url: http://www.comoves.unam.mx
  - name: Museode la Luz
    url: http://www.mudeodelaluz.unam.mx
  - name: Educacion continua
    url: https://educacioncontinua.dgdc.unam.mx
  - name: Temasili
    url: https://temasili.dgdc.unam.mx
  - name: UNAM
    url: https://www.unam.mx
  #- name: Google
  #  url: https://www.google.com
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co

assignees:
  - robertormzg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-dgdc
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoreo web Divulgacion de la Ciencia UNAM
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
